services:
  graph-node:
    image: graphprotocol/graph-node
    platform: linux/amd64
    network_mode: host
    depends_on:
      - ipfs
      - postgres
    env_file:
      - .env
    environment:
      ethereum: mainnet:${ETHEREUM_MAINNET}
      ipfs: "http://localhost:5001"
      postgres_host: localhost
      postgres_user: graph
      postgres_pass: letmein
      postgres_db: graph
      GRAPH_LOG: trace
      RUST_BACKTRACE: full

  ipfs:
    image: ipfs/go-ipfs:v0.15.0
    platform: linux/amd64
    ports:
      - "5001:5001"
    volumes:
      - ipfs_data:/data/ipfs

  postgres:
    image: postgres:14
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  pgdata:
  ipfs_data: